template: |
  ## What's Changed

  $CHANGES

categories:
  - title: '💥 Breaking'
    labels:
      - breaking
  - title: '✨ Features'
    labels:
      - enhancement
  - title: '🐛 Bugfixes'
    labels:
      - bug
  - title: '🧹 Housekeeping'
    labels:
      - housekeeping
