name-template: 'v$RESOLVED_VERSION'
template: |
  ## What's Changed

  $CHANGES

categories:
  - title: '💥 Breaking'
    label: breaking
  - title: '✨ Features'
    label: enhancement
  - title: '🐛 Bugfixes'
    label: bug
  - title: '🧹 Housekeeping'
    label: housekeeping
