name: Publish Release

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: geertvdc/setup-hub@v1.0.0
      - uses: actions/checkout@v2
      - run: |
          draft=$(hub release --include-drafts | grep untagged- | head -n1)
          echo "Draft tag: $draft"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



