name: Release

on:
  push:
    branches:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: check-version
        run: |
          current=$(node -p 'require("./package").version')
          git checkout HEAD~1
          previous=$(node -p 'require("./package").version')
          git checkout $GITHUB_REF
          if [[ "$current" != "$previous" ]]; then
            echo "::set-output name=new-version::$current"
          fi
      - if: steps.check-version.outputs.new-version
        run: |
          echo "Hey look a new version! ${{ steps.check-version.outputs.new-version }}"
      - run: |
          node --version
          ruby --version
