name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Check and Release New Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
        with:
          fetch-depth: 2

      - id: check-version
        name: Check for Version Change
        uses: dfreeman/action-detect-and-tag-new-version@v1

      - if: steps.check-version.outputs.tag
        name: Publish New Package Version
        run: |
          # This is where we'd `yarn publish`

      - if: steps.check-version.outputs.tag
        name: Publish Release Notes
        # We can switch to a tagged version once 5.8 is published
        uses: release-drafter/release-drafter@f677696
        with:
          publish: true
          tag: ${{ steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
