name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish New Version
        run: |
          echo "(Pretend this is where we'd run `yarn publish` or whatever)"
      - name: Publish Release Notes
        uses: dfreeman/release-drafter@allow-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
