name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish-package:
    name: Publish New Package Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "(Pretend this is where we'd run `yarn publish` or whatever)"
  publish-release-notes:
    name: Publish Release Notes
    steps:
      - uses: actions/checkout@v2
      - uses: dfreeman/release-drafter@allow-publish
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
