name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: check-version
        name: Check for Version Change
        run: |
          current=$(node -p 'require("./package").version')
          git checkout HEAD~1
          previous=$(node -p 'require("./package").version')
          git checkout $GITHUB_REF
          if [[ "$current" != "$previous" ]]; then
            git tag v$current
            git push --tags
          fi
