name: What

on:
  push:
    branches:
      - '*'

jobs:
  what:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dfreeman/release-playground@what
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



